"""Check the installed DEBUG gate keeps a command line that reads the inbox quiet.

The gate lives in the profile generated by the preview installer. This test rebuilds the
function from the installer source with a stub CLI, so it runs without touching the real
profile or state.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "skills" / "refs" / "arena-skill" / "scripts"))

import preview as preview_module

quiet_inbox_line = preview_module.quiet_inbox_line
INSTALLER = ROOT / "skills" / "refs" / "arena-skill" / "scripts" / "install.sh"

STUB = """#!/bin/sh
# The classifier is pure, so the stub answers with the real one.
if [ "$1" = "inbox-line" ]; then
  exec __PYTHON__ __PREVIEW__ inbox-line "$2"
fi
exit 1
"""


def gate_source() -> str:
  """Return the gate function as the installer writes it into the profile."""
  installer = INSTALLER.read_text(encoding="utf-8")
  match = re.search(
    r"# arena-preview-gate\n_arena_preview_gate\(\) \{.*?\n\}\nEOF",
    installer,
    re.DOTALL,
  )
  assert match, "installer must hold the gate function"
  block = match.group(0).removesuffix("\nEOF")
  # Unquoted heredocs drop one backslash before $, ` and backslash.
  block = block.replace("\\\\", "\x00").replace("\\$", "$").replace("\\`", "`")
  block = block.replace("\x00", "\\")
  return block.replace(
    '"$VENV/bin/python" "$REPO_ROOT/$SKILL_REL/scripts/preview.py"', '"$STUB"'
  )


def run(command: str, cwd: str | None = None) -> subprocess.CompletedProcess[str]:
  """Run one command in a shell whose $0 is bash, the shape the gate protects."""
  with tempfile.TemporaryDirectory() as directory:
    root = Path(directory)
    stub = root / "stub.sh"
    import sys

    preview_module = ROOT / "skills" / "refs" / "arena-skill" / "scripts" / "preview.py"
    stub.write_text(
      STUB.replace("__PYTHON__", sys.executable).replace(
        "__PREVIEW__", str(preview_module)
      ),
      encoding="utf-8",
    )
    stub.chmod(0o755)
    # The tested command line may call the real CLI for its answer. A stub on PATH
    # keeps that answer free of an installation, so the test runs anywhere.
    bin_dir = root / "bin"
    bin_dir.mkdir()
    cli = bin_dir / "arena-preview"
    cli.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    cli.chmod(0o755)
    # The gate body stays in a sourced file: its own pattern text must not reach the
    # shell command line, because the guard reads that line.
    gate_file = root / "gate.sh"
    gate_file.write_text(gate_source() + "\n", encoding="utf-8")
    script = (
      "set -o functrace\n"
      "STUB=" + str(stub) + "\n"
      "REPO_ROOT=" + str(ROOT) + "\n"
      "SKILL_REL=.agents/skills/arena-skill\n"
      '. "'
      + str(gate_file)
      + '"\n'
      + "trap '_arena_preview_gate : # arena-preview-gate' DEBUG\n"
      + command
      + "\n"
    )
    return subprocess.run(
      ["bash", "--noprofile", "--norc", "-c", script],
      capture_output=True,
      text=True,
      check=False,
      cwd=cwd,
      env={**os.environ, "PATH": str(bin_dir) + os.pathsep + os.environ["PATH"]},
    )


def test_plain_chain_meets_the_count_gate():
  result = run("cd /tmp && echo ran")
  assert result.returncode == 130, result.stderr
  assert "ran" not in result.stdout


def test_a_read_alone_stays_quiet():
  # The read must reach its read, whatever the tally.
  result = run(': "arena-preview read"')
  assert result.returncode == 0, result.stderr


def test_a_read_beside_work_meets_the_gate():
  # A read no longer licenses other calls: the work meets the gate first.
  result = run('cd /tmp && echo ran && : "arena-preview read"')
  assert result.returncode == 130, result.stderr
  assert "ran" not in result.stdout


def test_a_read_with_a_redirect_beside_work_meets_the_gate():
  result = run('cd /tmp && echo ran && : "arena-preview read" >/dev/null 2>&1')
  assert result.returncode == 130, result.stderr
  assert "ran" not in result.stdout


def test_an_ack_beside_work_meets_the_gate():
  result = run('cd /tmp && echo ran && : "arena-preview ack abc"')
  assert result.returncode == 130, result.stderr
  assert "ran" not in result.stdout


def test_chained_acks_stay_quiet():
  result = run(': "arena-preview ack a" && : "arena-preview ack b"')
  assert result.returncode == 0, result.stderr


def test_a_silenced_read_meets_the_count_gate():
  # A quiet chain that discards the reminder meets the gate like other work.
  result = run("cd /tmp && arena-preview read >/dev/null 2>&1")
  assert result.returncode == 130, result.stderr


def test_the_inbox_line_classifier():
  # Work beside an inbox call ends the exemption. Inert prefixes keep it.
  quiet = quiet_inbox_line
  assert quiet("")
  assert quiet("cd /x && arena-preview read")
  assert quiet("export PATH=/y; arena-preview read")
  assert quiet("arena-preview ack a; arena-preview ack b; arena-preview task x")
  assert quiet("arena-preview poll")
  assert quiet('arena-preview ack abc --reply "one line\ntwo lines"')
  assert quiet("arena-preview read 2>&1")
  assert not quiet("arena-preview read >/dev/null 2>&1")
  assert not quiet("arena-preview read > /dev/null 2>&1")
  assert not quiet("arena-preview read 2>/dev/null")
  assert not quiet("arena-preview ack abc &>/dev/null")
  assert not quiet('arena-preview ack abc --reply "$(rm -rf /tmp/x)"')
  # Single quotes never substitute in bash, so formatting and dollars ride an ack unchecked.
  # Double quotes keep their substitution refused (owner report report-stderr-read-investigation).
  assert quiet("arena-preview ack abc --reply 'task `x` is queued'")
  assert quiet("arena-preview ack abc --reply 'the $(pwd) path'")
  assert not quiet('arena-preview ack abc --reply "task `x` is queued"')
  assert not quiet('arena-preview ack abc --reply "the $(pwd) path"')
  assert not quiet("pytest -q; arena-preview read >/dev/null 2>&1")
  assert not quiet("cd /x && echo ran && arena-preview read")
  assert not quiet("git push origin main && arena-preview ack a")
  assert not quiet("echo hi | arena-preview read")


def test_push_in_a_quiet_chain_still_meets_the_push_gate():
  result = run("arena-preview read && git push origin branch")
  assert result.returncode == 130, result.stderr


def test_a_full_path_hears_the_bare_command_line():
  # The command sits on PATH in every shell the installer touched, so a call that
  # spells the path is told once, and the bare form is what reaches the log.
  spelled = f"{ROOT}/.agents/skills/arena-skill/scripts/arena-preview"
  result = run(f': "{spelled} read"')
  assert "arena-preview works" in result.stderr, result.stderr
  # One line a shell, not one a call.
  assert result.stderr.count("arena-preview works") == 1
  plain = run(': "arena-preview read"')
  assert "arena-preview works" not in plain.stderr


def test_an_unreachable_read_hears_the_proxy_line():
  # Code-scanning alerts and workflow run logs need the proxy, so the hook says so.
  result = run("gh api repos/o/r/code-scanning/alerts")
  assert "carries the routes" in result.stderr, result.stderr
  # One line a shell, not one a call.
  assert result.stderr.count("carries the routes") == 1
  logs = run("gh run view 7 --log")
  assert "carries the routes" in logs.stderr, logs.stderr
  plain = run("gh pr checks 7")
  assert "carries the routes" not in plain.stderr


def git_repo(root: Path) -> Path:
  """One repository whose origin/main carries a commit the branch lacks."""
  repo = root / "repo"
  repo.mkdir()
  environment = {
    **os.environ,
    "GIT_AUTHOR_NAME": "t",
    "GIT_AUTHOR_EMAIL": "t@t",
    "GIT_COMMITTER_NAME": "t",
    "GIT_COMMITTER_EMAIL": "t@t",
  }

  def git(*args: str) -> None:
    subprocess.run(
      ["git", *args],
      cwd=repo,
      env=environment,
      capture_output=True,
      text=True,
      check=True,
    )

  git("init", "-q", "-b", "work")
  git("config", "user.name", "t")
  git("config", "user.email", "t@t")
  (repo / "a").write_text("one\n", encoding="utf-8")
  git("add", "a")
  git("commit", "-qm", "one")
  (repo / "b").write_text("two\n", encoding="utf-8")
  git("add", "b")
  git("commit", "-qm", "two")
  git("update-ref", "refs/remotes/origin/main", "HEAD")
  git("reset", "-q", "--hard", "HEAD~1")
  return repo


def test_a_branch_behind_main_hears_the_replay_line():
  with tempfile.TemporaryDirectory() as directory:
    repo = git_repo(Path(directory))
    result = run("git commit --allow-empty -m three", cwd=str(repo))
    assert result.returncode == 0, result.stderr
    assert "origin/main carries 1 commit(s) this branch lacks" in result.stderr
    assert "Replay your commits over main" in result.stderr
    # A replayed branch: origin/main is no longer ahead, and the line stays away.
    subprocess.run(
      ["git", "update-ref", "refs/remotes/origin/main", "HEAD"],
      cwd=repo,
      capture_output=True,
      check=True,
    )
    result = run("git commit --allow-empty -m four", cwd=str(repo))
    assert result.returncode == 0, result.stderr
    assert "Replay your commits over main" not in result.stderr


def shallow_repo(root: Path, *, lone_tip: bool) -> Path:
  """Return one repository whose graft hides the remote tip's history.

  The branch root sits in .git/shallow, the shape a depth-one fetch leaves. The
  remote tip is either a lone root commit or a two-commit line whose parent is
  visible locally.
  """
  repo = root / "repo"
  repo.mkdir()
  environment = {
    **os.environ,
    "GIT_AUTHOR_NAME": "t",
    "GIT_AUTHOR_EMAIL": "t@t",
    "GIT_COMMITTER_NAME": "t",
    "GIT_COMMITTER_EMAIL": "t@t",
  }

  def git(*args: str) -> str:
    result = subprocess.run(
      ["git", *args],
      cwd=repo,
      env=environment,
      capture_output=True,
      text=True,
      check=True,
    )
    return result.stdout.strip()

  git("init", "-q", "-b", "work")
  git("config", "user.name", "t")
  git("config", "user.email", "t@t")
  (repo / "a").write_text("one\n", encoding="utf-8")
  git("add", "a")
  git("commit", "-qm", "one")
  (repo / "b").write_text("two\n", encoding="utf-8")
  git("add", "b")
  git("commit", "-qm", "two")
  branch_root = git("rev-parse", "HEAD")
  git("checkout", "-q", "--orphan", "remote")
  git("rm", "-q", "-rf", "--cached", ".")
  (repo / "t").write_text("tip\n", encoding="utf-8")
  git("add", "t")
  git("commit", "-qm", "tip-old")
  tip = git("rev-parse", "HEAD")
  if not lone_tip:
    (repo / "u").write_text("more\n", encoding="utf-8")
    git("add", "u")
    git("commit", "-qm", "tip-new")
    tip = git("rev-parse", "HEAD")
  git("checkout", "-qf", "work")
  git("update-ref", "refs/remotes/origin/main", tip)
  # A graft at the branch root is what a depth-one fetch leaves behind.
  (repo / ".git" / "shallow").write_text(branch_root + "\n", encoding="utf-8")
  return repo


def test_a_lone_grafted_tip_keeps_the_drift_line_quiet():
  # One commit with no parents proves nothing about main, so the count stays
  # unspoken (owner note 94e3313).
  with tempfile.TemporaryDirectory() as directory:
    repo = shallow_repo(Path(directory), lone_tip=True)
    assert (repo / ".git" / "shallow").exists()
    result = run("git commit --allow-empty -m three", cwd=str(repo))
    assert result.returncode == 0, result.stderr
    assert "origin/main carries" not in result.stderr, result.stderr
    assert "Replay your commits over main" not in result.stderr, result.stderr


def test_a_grafted_tip_with_visible_history_hears_the_replay_line():
  # The tip's own parent is present, so the count speaks for main.
  with tempfile.TemporaryDirectory() as directory:
    repo = shallow_repo(Path(directory), lone_tip=False)
    result = run("git commit --allow-empty -m three", cwd=str(repo))
    assert result.returncode == 0, result.stderr
    assert "origin/main carries 2 commit(s) this branch lacks" in result.stderr, (
      result.stderr
    )
    assert "Replay your commits over main" in result.stderr
