"""Check the installed DEBUG gate keeps a command line that reads the inbox quiet.

The gate lives in the profile generated by the preview installer. This test rebuilds the
function from the installer source with a stub CLI, so it runs without touching the real
profile or state.
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INSTALLER = (
  ROOT / "skills" / "refs" / "arena-preview-steering" / "scripts" / "install.sh"
)

STUB = """#!/bin/sh
if [ "$1" = "gate" ] && [ "$2" = "--push" ]; then
  exit 1
fi
exit 1
"""


def gate_source() -> str:
  """Return the gate function as the installer writes it into the profile."""
  installer = INSTALLER.read_text(encoding="utf-8")
  match = re.search(
    r"# arena-preview-gate\n_arena_preview_gate\(\) \{.*?\n\}\nEOF",
    installer,
    re.DOTALL,
  )
  assert match, "installer must hold the gate function"
  block = match.group(0).removesuffix("\nEOF")
  # Unquoted heredocs drop one backslash before $, ` and backslash.
  block = block.replace("\\\\", "\x00").replace("\\$", "$").replace("\\`", "`")
  block = block.replace("\x00", "\\")
  return block.replace(
    '"$VENV/bin/python" "$REPO_ROOT/$SKILL_REL/scripts/preview.py"', '"$STUB"'
  )


def run(command: str) -> subprocess.CompletedProcess[str]:
  """Run one command in a shell whose $0 is bash, the shape the gate protects."""
  with tempfile.TemporaryDirectory() as directory:
    root = Path(directory)
    stub = root / "stub.sh"
    stub.write_text(STUB, encoding="utf-8")
    stub.chmod(0o755)
    # The gate body stays in a sourced file: its own pattern text must not reach the
    # shell command line, because the guard reads that line.
    gate_file = root / "gate.sh"
    gate_file.write_text(gate_source() + "\n", encoding="utf-8")
    script = (
      "set -o functrace\n"
      "STUB=" + str(stub) + "\n"
      '. "'
      + str(gate_file)
      + '"\n'
      + "trap '_arena_preview_gate : # arena-preview-gate' DEBUG\n"
      + command
      + "\n"
    )
    return subprocess.run(
      ["bash", "--noprofile", "--norc", "-c", script],
      capture_output=True,
      text=True,
      check=False,
    )


def test_plain_chain_meets_the_count_gate():
  result = run("cd /tmp && echo ran")
  assert result.returncode == 130, result.stderr
  assert "ran" not in result.stdout


def test_chain_that_names_a_read_stays_quiet():
  result = run('cd /tmp && echo ran && : "arena-preview read"')
  assert result.returncode == 0, result.stderr
  assert "ran" in result.stdout


def test_chain_that_names_an_ack_stays_quiet():
  result = run('cd /tmp && echo ran && : "arena-preview ack abc"')
  assert result.returncode == 0, result.stderr
  assert "ran" in result.stdout


def test_push_in_a_quiet_chain_still_meets_the_push_gate():
  result = run(
    'cd /tmp && echo ran && : "arena-preview read" && git push origin branch'
  )
  assert result.returncode == 130, result.stderr
